export enum FriendStatusInvitation {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  PENDINGSENDBYME = 'PENDINGSENDBYME',
  PENDINGRECEIVED = 'PENDINGRECEIVED',
  NOTFRIEND = 'NOTFRIEND',
}

export enum FriendStatusIndexEnum {
  ACCEPTED = 0,
  PENDING = 1,
  REJECTED = 2,
}
