services:
  postgres:
    container_name: chatter-db
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 'chatter'
      POSTGRES_USER: 'chatter'
      POSTGRES_DB: 'chatter-db'
    ports:
      - '5700:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
